import './styles'
import 'components/Button/Button.scss';
import 'components/Header/Header.scss';
import 'components/Container/Container.scss';
import 'components/Section/Section.scss';
import 'components/Error/Error.scss';
import 'components/Footer/Footer.scss';
import 'components/ProgramCard/ProgramCard.scss';
import 'components/PrivacyPolicy/PrivacyPolicy.scss';
import 'components/Icon/Icon.scss';
import 'components/ProgramPage/ProgramPage.scss';
import 'components/DayProgram/DayProgram.scss';
import 'components/ExerciseVideoPrev/ExerciseVideoPrev.scss';
import 'components/RecipeCard/RecipeCard.scss';
import 'components/RecipePage/RecipePage.scss';
import 'components/Pagination/Pagination.scss';
import 'components/RecipesHeader/RecipesHeader.scss';
import 'components/RecipeLatest/RecipeLatest.scss';
import 'components/RecipesWrapper/RecipesWrapper.scss';
