import './styles'
import 'components/Button/Button.scss';
import 'components/Header/Header.scss';
import 'components/Container/Container.scss';
import 'components/Section/Section.scss';
import 'components/Error/Error.scss';
import 'components/Footer/Footer.scss';
import 'components/ProgramCard/ProgramCard.scss';
import 'components/PrivacyPolicy/PrivacyPolicy.scss';
import 'components/Icon/Icon.scss';
